#!/bin/bash -x

OSNAME="$(uname -s)"

# tmux ls
# tmux detach ctrl+b d
# tmux a //athach to unique session
# tmux a -t grabakey
case $1 in
  # dev station remote commands
  deploy)
    if [[ ! "$OSNAME" =~ "Linux" ]]; then
      echo "Linux required to deploy"
      exit
    fi
    MIX_ENV=prod mix release --overwrite
    rsync grabakey grabakey.org:bin/
    ssh grabakey.org bin/grabakey stop 
    ssh grabakey.org bin/grabakey setup 
    # remove old priv files (duplicated migration)
    rsync --delete -r _build/prod/rel/grabakey/ grabakey.org:grabakey/backend
    ssh grabakey.org bin/grabakey start 
  ;;
  fetch-backup)
    rm .database/grabakey_dev.*
    ssh grabakey.org sqlite3 grabakey/database/grabakey_rel.db '".backup /tmp/gak-backup.db"'
    scp grabakey.org:/tmp/gak-backup.db .database/grabakey_dev.db
    #sqlite3 .database/grabakey_dev.db "select * from users"
  ;;
  fetch-dump)
    rm .database/grabakey_dev.*
    ssh grabakey.org sqlite3 grabakey/database/grabakey_rel.db ".dump" | sqlite3 .database/grabakey_dev.db
    #sqlite3 .database/grabakey_dev.db "select * from users"
  ;;
  # dev station local commands
  local)
    # sshuttle -r grabakey.org 0.0.0.0/0
    MIX_ENV=prod mix release --overwrite
    export GAK_MAILER_ENABLED=true
    export GAK_DATABASE_PATH=.database/grabakey_rel.db 
    _build/prod/rel/grabakey/bin/grabakey start
  ;;
  # server local commands
  letsencrypt)
    V2="--server https://acme-v02.api.letsencrypt.org/directory"
    sudo service nginx stop
    sudo letsencrypt certonly --standalone -d grabakey.org --force-renew $V2
    sudo letsencrypt certonly --standalone -d www.grabakey.org --force-renew $V2
    sudo service nginx start  
  ;;
  setup)
    mkdir -p ~/grabakey/backend/
    mkdir -p ~/grabakey/database/
  ;;
  start)
    export GAK_MAILER_ENABLED=true
    export GAK_DATABASE_PATH=~/grabakey/database/grabakey_rel.db 
    tmux new -d -s grabakey ~/grabakey/backend/bin/grabakey start
  ;;
  stop)
    ~/grabakey/backend/bin/grabakey stop
  ;;
  *)
    ~/grabakey/backend/bin/grabakey "$@"
  ;;
esac
